# Generated by Django 5.1.5 on 2025-02-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_flavour', models.CharField(default=None, max_length=64, null=True)),
                ('ice_cream_name', models.CharField(default=None, max_length=64, null=True)),
                ('ice_cream_weight', models.CharField(default=None, max_length=16, null=True)),
                ('entry_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
